---
output:
  html_document:
    keep_md: yes
---
DATA DICTIONARY - HUMAN ACTIVITY RECOGNITION USING SMARTPHONES DATASET
=======================================================================

FYI: I don't understand the feature_info.txt file well, so there was little I can do with 
the code book. Check the feature_info.txt for details.

"Activity"

 Walking
 
 WalkingUp: Walking Upstairs
 
 WalkingDown: Walking Downstaris
 
 Sitting
 
 Standing
 
 Laying
 
"SubjectID"
 
 A list of numbers from 1 to 30, each number represents a subject.
 
"tBodyAcc-mean()-X"
 
 The mean of tBodyAcc from X axis 
 
"tBodyAcc-mean()-Y"
 
 The mean of tBodyAcc from Y axis 

"tBodyAcc-mean()-Z"
 
 The mean of tBodyAcc from Z axis 

"tBodyAcc-std()-X"
 
 The standard deviation of tBodyAcc from X axis 

"tBodyAcc-std()-Y"
 
 The standard deviation of tBodyAcc from Y axis 

"tBodyAcc-std()-Z"
 
 The standard deviation of tBodyAcc from Z axis 

"tGravityAcc-mean()-X"
 
 The mean of tGravityAcc from X axis 

"tGravityAcc-mean()-Y"
 
 The mean of tGravityAcc from Y axis

"tGravityAcc-mean()-Z"
 
 The mean of tGravityAcc from Z axis

"tGravityAcc-std()-X"
 
 The standard deviation of tGravityAcc from X axis

"tGravityAcc-std()-Y"

 The standard deviation of tGravityAcc from Y axis
 
"tGravityAcc-std()-Z"

 The standard deviation of tGravityAcc from Z axis
 
"tBodyAccJerk-mean()-X"

 The mean of tBodyAccJerk from X axis
 
"tBodyAccJerk-mean()-Y"

 The mean of tBodyAccJerk from Y axis
 
"tBodyAccJerk-mean()-Z"

 The mean of tBodyAccJerk from Z axis
 
"tBodyAccJerk-std()-X"

 The mean of tBodyAccJerk from X axis
 
"tBodyAccJerk-std()-Y"

 The mean of tBodyAccJerk from X axis
 
"tBodyAccJerk-std()-Z"

 The mean of tBodyAccJerk from X axis
 
"tBodyGyro-mean()-X"

 The mean of tBodyAccJerk from X axis
 
"tBodyGyro-mean()-Y"

 The mean of tBodyAccJerk from X axis
 
"tBodyGyro-mean()-Z"
 
 The mean of tBodyAccJerk from X axis
 
"tBodyGyro-std()-X"

 The mean of tBodyAccJerk from X axis
 
"tBodyGyro-std()-Y"

 The mean of tBodyAccJerk from X axis
 
"tBodyGyro-std()-Z"

 The mean of tBodyAccJerk from X axis
 
"tBodyGyroJerk-mean()-X"

 The mean of tBodyAccJerk from X axis
 
"tBodyGyroJerk-mean()-Y"

 The mean of tBodyAccJerk from X axis
 
"tBodyGyroJerk-mean()-Z"

 The mean of tBodyAccJerk from X axis
 
"tBodyGyroJerk-std()-X"

 The mean of tBodyAccJerk from X axis
 
"tBodyGyroJerk-std()-Y"

 The mean of tBodyAccJerk from X axis
 
"tBodyGyroJerk-std()-Z"

 The mean of tBodyAccJerk from X axis
 
"tBodyAccMag-mean()"

The mean of tBodyAccJerk from X axis

"tBodyAccMag-std()"

The mean of tBodyAccJerk from X axis

"tGravityAccMag-mean()"

The mean of tBodyAccJerk from X axis

"tGravityAccMag-std()"

The mean of tBodyAccJerk from X axis

"tBodyAccJerkMag-mean()"

The mean of tBodyAccJerk from X axis

"tBodyAccJerkMag-std()"

The mean of tBodyAccJerk from X axis

"tBodyGyroMag-mean()"

The mean of tBodyAccJerk from X axis

"tBodyGyroMag-std()"

The mean of tBodyAccJerk from X axis

"tBodyGyroJerkMag-mean()"

The mean of tBodyAccJerk from X axis

"tBodyGyroJerkMag-std()"

The mean of tBodyAccJerk from X axis

"fBodyAcc-mean()-X"

The mean of tBodyAccJerk from X axis

"fBodyAcc-mean()-Y"

The mean of tBodyAccJerk from X axis

"fBodyAcc-mean()-Z"

The mean of tBodyAccJerk from X axis

"fBodyAcc-std()-X"

The mean of tBodyAccJerk from X axis

"fBodyAcc-std()-Y"

The mean of tBodyAccJerk from X axis

"fBodyAcc-std()-Z"

The mean of tBodyAccJerk from X axis

"fBodyAccJerk-mean()-X"

The mean of tBodyAccJerk from X axis

"fBodyAccJerk-mean()-Y"

The mean of tBodyAccJerk from X axis

"fBodyAccJerk-mean()-Z"

The mean of tBodyAccJerk from X axis

"fBodyAccJerk-std()-X"

The mean of tBodyAccJerk from X axis

"fBodyAccJerk-std()-Y"

The mean of tBodyAccJerk from X axis

"fBodyAccJerk-std()-Z"

The mean of tBodyAccJerk from X axis

"fBodyGyro-mean()-X"

The mean of tBodyAccJerk from X axis

"fBodyGyro-mean()-Y"

The mean of tBodyAccJerk from X axis

"fBodyGyro-mean()-Z"

The mean of tBodyAccJerk from X axis

"fBodyGyro-std()-X"

The mean of tBodyAccJerk from X axis

"fBodyGyro-std()-Y"

The mean of tBodyAccJerk from X axis

"fBodyGyro-std()-Z"

The mean of tBodyAccJerk from X axis

"fBodyAccMag-mean()"

The mean of tBodyAccJerk from X axis

"fBodyAccMag-std()"

The mean of tBodyAccJerk from X axis

"fBodyBodyAccJerkMag-mean()"

The mean of tBodyAccJerk from X axis

"fBodyBodyAccJerkMag-std()"

The mean of tBodyAccJerk from X axis

"fBodyBodyGyroMag-mean()"

The mean of tBodyAccJerk from X axis

"fBodyBodyGyroMag-std()"

The mean of tBodyAccJerk from X axis

"fBodyBodyGyroJerkMag-mean()"

The mean of tBodyAccJerk from X axis

"fBodyBodyGyroJerkMag-std()"

The mean of tBodyAccJerk from X axis
